print("hello")
print("hello world, good bye")
print("test1, testing")
print("hello world, good bye")

print("hello. OK")
print("task8")
print("task9")
print("task2")
print("task3")
print("task10")
print("task11")